### ISSUE TITLE
index.js uses relative file paths for readFileSync

### ISSUE THREAD

**Issue by cjrd** [tjwebb/pg-json-schema-export#6]
https://github.com/tjwebb/pg-json-schema-export/blob/master/index.js#L7
and
https://github.com/tjwebb/pg-json-schema-export/blob/master/index.js#L8

causes 
`Error: ENOENT, no such file or directory './sql/views.sql'` 
when requiring pg-json-schema-export from another directory.

Potential fix would be to use `__dirname + "/sql/..."` 

rather than "./sql/..."

**Comment by tjwebb** [comment]
I think this should be resolved. Publishing new version to npm now.

**Comment by cjrd** [comment]
confirmed: this resolved my issue
